<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class AI extends CI_Controller {

    public function __construct() {
        parent::__construct();
        $this->load->model('AI_Model'); // Load your AI model
    }

    public function index() {
        // Load the view with the input form
        $this->load->view('generate_view');
    }

    public function generate() {
        // Get input from the form
        $prompt = $this->input->post('prompt');

        // Generate content using AI model
        $generated_content = $this->AI_Model->generateContent($prompt);

        // Display the generated content (you can modify this as per your application)
        echo $generated_content;
    }
    
    public function generate2(){
    
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/chat/completions');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
$postData=array(
  "model"=> "gpt-3.5-turbo-1106",
  "messages"=> [
    
      "role"=> "user",
      "content"=> [
        
          "type"=> "text",
          "text"=> "t-shirt product description and title\n"
        
      ]
    
  ],
  "temperature"=> 1,
  "max_tokens"=> 256,
  "top_p"=> 1,
  "frequency_penalty"=> 0,
  "presence_penalty"=> 0  
);
$postData=json_encode($postData);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer sk-proj-SoBqVeNTXMyFdMnSF3ydT3BlbkFJV0sE2eNA4q5H3LSKJcMD';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
$result=json_decode($result,true);
echo "<pre>";
print_r($result);
    }
}
