<?php 
$list = $this->db->get("refund_policy")->row();	
?>
<!DOCTYPE html>
<html class="no-js" lang="zxx">
	
	<head>
		<meta charset="UTF-8">
			<title><?= $list->refund_title?></title>
		<meta name="description" content="<?= $list->refund_description?>">
		<meta name="keywords" content="<?= $list->refund_keyword?>">
		<meta name="author" content="">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<?php include('include/cssLinks.php') ?>
		<style>
			.icon {
			font-size: 2rem;
			}	
			.slide-toggle{
			display:none!important;
			}
			.table th, .table td {
			padding-left: 6px;
			}
			
		</style>
		
	</head>
    
    <body>  
		<!-- Paste this code after body tag -->
		
		
		<!-- //Header Style One -->
		
		<?php include('include/header.php') ?>
		
		<div class="container-fuild">
			<nav aria-label="breadcrumb">
				<div class="container">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="<?= base_url(); ?>">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">Refund Policy</li>
					</ol>
				</div>
			</nav>
		</div> 
		<section class="pro-content login-content">
			<div class="container">
				<div class="row">
					<div class="col-sm-4 mx-auto">
						<center><img src="https://cdn.shopify.com/s/files/1/2337/7003/files/New_Project_12_256x256_crop_center.png?v=1624868361"></center>
						<!--<h2 class="text-center mt-2">REFUND POLICY</h2>-->
					</div>  
				</div> 
				<!--<h1 class="text-center">HOW TO FILE FOR A REFUND?</h1>
				<p class="text-justify">To apply for a Refund against an order please email us your order # with product name, original proof of purchase receipt (proof of payment) and your complaint/reason/issue for requesting a refund at customercare@SlickPattern.pk and our customer care agent will get in contact with you. Alternatively you can call us on +92 316 7776158 from Monday to Saturday between 10:00 am - 6:00 pm (Pakistan Standard Time). Further, to proceed with the Refund against a purchase case, your purchase should be sent back to us within 14 days of receiving your order.</p>-->
				<?= $list->refund_policy; ?>
				
				<div class="row">
					<div class="col-sm-4 mx-auto">
						<div class="form-group">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">	
										<input type="text" class="form-control forn-control-lg" required placeholder="Order Number">
									</div>
								</div>   
								<div class="col-lg-6">
									<div class="form-group">	
										<input type="text" class="form-control forn-control-lg" required placeholder="Email">
									</div>
								</div>   
							</div>	 
						</div>
						<div class="form-group">
							<input type="text" name="product_name" class="form-control forn-control-lg" required placeholder="Product Name">	 
						</div>
						<div class="form-group">
							<select class="form-control forn-control-lg" required>
							<option value="selected disabled">Request of refund</option>  
						</select> 
						</div>
						<div class="form-group mr-5 ml-5">
						<p class="text-center"><button class="btn btn-secondary btn-block">Send</button></p>	 
						</div>
					</div>  
					</div>
					<br>
					<?= $list->refund_policy2; ?>
					<!--h2 class="text-center">REFUND  PROCEDURE</h2>
					<p class="text-justify">In case you want to claim a refund from SlickPattern, kindly follow below given steps :</p>
					<ul>
					<li>Contact our customer care via WhatsApp/ Email Id or reach out to us on customercare@SlickPattern.pk</li>
					<li>Provide our customer care staff with your order number and original order confirmation receipt sent to you via email, proof of payment Order Confirmations & Receipts are automatically generated by our system and sent out to the email ID provided by the customer once the customer checks out and completes the order purchase process on our website.</li>
					<li>Submit a request and a detailed reason/complaint/issue for requesting for a Refund claim.</li>
					
					</ul>
					<br>
					<h2 class="text-center">ELIGIBILITY CRITERIA FOR A REFUND:</h2>
					<p class="text-justify">SlickPattern caters refund for following mentioned reasons,</p>
					<p class="text-justify">Delayed by brand : If 14 working days have passed since your estimated delivery timeline provide by SlickPattern at time of purchase confirmation, given that vendor is allowed to change the estimated delivery timeline only once, due to any reason that may affect production implied by designer/brand, government order or an act of God, when the customer is pre-informed either by the SlickPattern’s team or designer’s team.</p>
					<p class="text-justify">Out of stock : If the brand/vendor notifies us that your preferred item is being out of stock/ out of production and can no longer be made available in the future.</p>
					<p class="text-justify">Return : In case you have filed for return and we have approved and received your return in any of our SlickPattern warehouses and not the designer’s then it is eligible for refund. In such cases, SlickPattern will only refund the cost of the product and not bear charges for courier, return-shipping, or any amendments and stitching done to the product by the customer. In case a parcel has been stuck in customs and is returned back to the SlickPattern warehouse, then shipping charges are non-refundable.</p>
					<p class="text-justify">Exchange : If you have exchanged/ replaced your outfit with another outfit available in stock on our website and there is a pending balance amount at our end. In such cases we will refund your amount or provide you with store credit as per your preference.
					Post delivery issues :</p>
					<ul>
					<li>First 24 hours after delivery of the Order : Client has to report a complaint.</li>	
					<li>Next 24 hours after reporting a complaint : Client has to provide proof of their refund claim in the form of pictures, videos or any other compelling evidence.
					Next 24 hours after providing the proof : Client must provide a return receipt once the case manager has approved the return.Issue in payment :</li>	
					<li>If your order is made to order then refunds won't be catered after your order has gone into production i.e. After 48 hours of order confirmation, the made to order articles cannot be refunded.</li>	
					<li>Some Brands/Vendors/Designers do not offer refund option on certain articles from their Luxury Pret/Formals/Bridals collections although in standard sizes due to their price point and therefore SlickPattern would not be able to refund those article.</li>	
					</ul>
					
					<br>
					<h2 class="text-center">NON ELIGIBILITY CRITERIA FOR A REFUND</h2>
					<p class="text-justify">Outfit is not-eligible for refund/return/exchange in following cases</p>
					<p class="text-justify">Violation of Care instructions</p>
					<p class="text-justify">Following points will be considered as violation of care instructions :</p>
					<ul>
					<li>If the outfit has been shrunk.</li>	
					<li>If the outfit has been washed/ dry clean.</li>	
					<li>If an outfit has been stitched even in cases of missing pieces.</li>	
					<li>If the outfit has been worn or tried on..</li>	
					<li>If the item has been subjected to bleach/chemical for stain removing.</li>	
					<li>A list of care instructions are provided by the designer and if any of those instructions are also not followed properly then the order is not eligible for a refund.</li>	
					</ul>
					<p class="text-justify"><strong>Inability to provide the Proof :</strong> If no proof has been provided in support of the claim of ‘eligibility’ within the 24 hours.</p>
					<p class="text-justify"><strong>Timeline for sharing Return Receipt slip :</strong>  If return has been accepted and return receipt is not shared within the given time period of acceptance of the refund.</p>
					<p class="text-justify"><strong>Packaging is tamperedlip :</strong>  Orders are not eligible for refund, return or exchange, if packaging is opened, damaged or tampered at the time of receiving by the customer.</p>
					<p class="text-justify"><strong>Sale Price Adjustment  :</strong>  SlickPattern does not cater requests for price change in case a customer has bought an article before sale at original price and wants to be compensated with a refund for the difference in price after the sale has been implied.</p>
					<p class="text-justify"><strong>Change of mind  :</strong>  SlickPattern does not cater “CHANGE OF MIND/ NO LONGER NEEDED/ NO TECHNICAL REASON BUT JUST WANT TO CANCEL THE ORDER/ DIDN’T LIKE THE PRODUCT AFTER OPENING THE PACKAGE/ ORDER BY MISTAKE” as reason for cancellation/refund/exchange if reported after 48 hours of placing the order.</p>
					<p class="text-justify"><strong>Advance Payment Clause  :</strong> Any amount paid as ‘ advance payment’ for bridal/couture orders is non-refundable and non-transferrable</p>
					<p class="text-justify"><strong>Product is gone on Sale Price Afterwards :</strong> SlickPattern does not offer price-match or price adjustment policy once the item has gone on sale after Order Confirmation/ Payment Confirmation.</p>
					<p class="text-justify"><strong>Active Chargeback :</strong>  Refund can’t be issued as long as a chargeback/dispute on the payment is active and the case is in progress</p>
					<p class="text-justify"><strong>Pre-Booking & Out of stock Items:</strong>  Please be aware that we may be unable to deliver selected advance payment merchandise due to production problems or quality checks issues identified when we receive an order into stock. In these circumstances we will notify you and refund the advance payment to your debit/credit card within thirty days of being advised that merchandise has become unavailable.
					<br>
					Order stuck in Customs</p>
					<br>
					<h2 class="text-center">REFUND DISCLAIMERS :</h2>
					<ul>
					<li>SlickPattern offers you the right either to take your refund in form of cash return or store credit that can be used for future purchase.</li>	
					<li>Please note in case you have been catered with store credit for an order then you will not be considered eligible for refund for the same order.</li>	
					<li>Once store credit has been issued it will not be reversed/exchanged with a refund.</li>	
					
					</ul>
					<br>
					<h2 class="text-center">REFUNDS WHEN SELLING IN MULTIPLE CURRENCIES :</h2>
					<p class="text-justify">Refunds are always issued to a customer in the currency that they used to pay for the order. When we issue refunds, the following rules apply :</p>
					
					<ul>
					<li>Refunds use the same payment method that was used to pay for the order. We cannot issue a refund to a different card or bank a count.</li>	
					<li>Refunds are issued in the same currency that the customer used to pay for the order. If the customer paid in Euros, then they receive a refund in Euros.</li>	
					<li>If the currency needs to be converted for the refund, then the current currency rate, and not the currency rate at the time of the order, is used in the conversion. You're charged a currency conversion fee when the payment is converted, but not when a refund is issued. Currency conversion fees and credit card fees aren't returned to you when you issue a refund.</li>	
					<li>If we use a manual conversion rate, then refunds are calculated using the currency rate at the time of the order and not the current currency rate.
					Timeline for Refund : 14 days to 45 days</li>	
					</ul>
					<div class="row">
					<div class="col-sm-6 mx-auto">
					<table class="table table-bordered"> 
					<tbody> 
					<tr>
					<td>Payment method</td>   
					<td>Refund option</td>   
					<td>Refund time</td>   
					</tr>
					<tr>
					<td>Debit/ Credit Card</td>   
					<td>Debit/ Credit Card</td>   
					<td>7-14 business days</td>   
					</tr>
					<tr>
					<td>Direct bank transfer</td>   
					<td>Direct bank transfer Store Credit Voucher</td>   
					<td>7-14 business days 2 days</td>   
					</tr>
					<tr>
					<td>COD</td>   
					<td>Voucher/ Store credit</td>   
					<td>2  business days</td>   
					</tr>
					<tr>
					<td>Quickpay Zelle/ Western Union/ Moneygram</td>   
					<td>Chase Bank/ Zelle</td>   
					<td>5  business days.</td>   
					</tr>
					</tbody> 
					</table>
					</div>	
					</div>
					<br>
					<h2 class="text-center">COD ORDERS</h2>
					<p class="text-justify">Orders paid on cash on delivery are only refunded if by any chance the customer mistakenly paid the amount twice, once via bank deposit and once as cash while receiving the parcel,For such cases you need to report within an allotted time mentioned in our policy. Our case manager will review your request if it gets approved you will be notified and your refund will be processed within 10 business days.</p>
					
					<h2 class="text-center">PAID ORDERS</h2>
					<p class="text-justify">Paid orders are only refunded if reported within an allotted time mentioned in our policy and the customer provides proof of evidence and proof of payment for requesting a refund. Refund Case Manager will look at your case and will respond within 5 business days whether your request has been approved or rejected for refund. Refund will be approved based on the eligibility clauses and rejected on the basis of non-eligibility clauses.</p>
					
					<h2 class="text-center">PARTIAL PAYMENT ORDERS</h2>
					
					<p class="text-justify">Incase of a Bridal order, any amount paid as ‘ advance payment’ for bridal/couture orders is non-refundable and non-transferrable. If you wish to file for a refund, once the order has completed the production phase or is in the final phases of production and/or is received in our warehouse, SlickPattern will deduct 50% of your paid amount as cost of production, labor, and resources has already incurred by the brand and SlickPattern has already paid that amount to the brand for your order to go into production.</p>
					
					<h2 class="text-center">PRE BOOKING ORDERS</h2>
					
					<p class="text-justify">You may from time to time be given the possibility of making an advance payment for certain items in which case you are able to make an advance purchase. This will ensure that you receive this item in priority once designer stock has been delivered to us. We will only take advance purchase orders for stock that has been scheduled for delivery by a designer supplier. Your rights regarding advance purchase are the same as those for any other purchase on our site. Refund is eligible to be issued if there are any delays in the delivery timeline from the designers end and the customer is timely informed of such delay and the customer has the right to exercise the change of mind option and request for a refund. Refunds will not be issued once the pre-booked item has been dispatched from the warehouse, shipped & delivered to the customer.</p>
					
					<h2 class="text-center">READY TO SHIP ORDERS</h2>
					
					<p class="text-justify">Ready to Ship orders are only refunded if reported within an allotted time mentioned in our policy and the customer provides proof of evidence and proof of payment for requesting a refund. Refund Case Manager will look at your case and will respond within 5 business days whether your request has been approved or rejected for refund. Refund will be approved based on the eligibility clauses and rejected on the basis of non-eligibility clauses. Refunds will not be issued once the pre-booked item has been dispatched from the warehouse, shipped & delivered to the customer.</p>
					
					<h2 class="text-center">MADE TO ORDER/CUSTOMIZED ORDERS</h2>
					
					<p class="text-justify">You do not have a right to change your mind in respect of items which are made to order, bespoke or personalised.Incase of a Bridal order, any amount paid as ‘ advance payment’ for bridal/couture orders is non-refundable and non-transferrable.If your order is made to order then refunds won't be catered after your order has gone into production i.e. After 48 hours of order confirmation, the made to order articles cannot be refunded.Some Brands/Vendors/Designers do not offer refund option on certain articles from their Luxury Pret/Formals/Bridals collections although in standard sizes due to their price point and therefore SlickPattern would not be able to refund those article.</p>
					
					<h2 class="text-center">OUT OF STOCK ORDERS</h2>
					
					<p class="text-justify">We will contact you in advance to tell you we will be suspending supply of the product, unless the problem is urgent or an emergency. You may contact us to end the contract for a product if we suspend it, or tell you we are going to suspend it and we will refund any sums you have paid in advance for the product in respect of the period after you end the contract.</p>
					<p class="text-justify">If our supply of the products is delayed by an event outside our control then we will contact you as soon as possible to let you know and we will take steps to minimise the effect of the delay. Provided we do this we will not be liable for delays caused by the event, but if there is a risk of substantial delay you may contact us to end the contract and receive a refund for any products you have paid for but not received.</p-->
					
					
					</div>
					</section>
					
					
					
					
					
					
					<?php include('include/footer.php'); ?>
					
					
					
					<?php include('include/jsLinks.php'); ?>
					
					</body>
					</html>																																												