<?php 
$list = $this->db->get("return_policy")->row();	
?>
<!DOCTYPE html>
<html class="no-js" lang="zxx">
	
	<head>
		<meta charset="UTF-8">
		<title><?= $list->return_title?></title>
		<meta name="description" content="<?= $list->return_description?>">
		<meta name="keywords" content="<?= $list->return_keyword?>">
		<meta name="author" content="">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<?php include('include/cssLinks.php') ?>
		<style>
			.icon {
			font-size: 2rem;
			}
			.slide-toggle{
			display:none!important;
			}
			@media only screen and (max-width: 600px) {
			.pageheading{
			font-size: 20px!important;
			}
			}
		</style>
		
	</head>
    
    <body>  
		<!-- Paste this code after body tag -->
		
		
		<!-- //Header Style One -->
		
		<?php include('include/header.php') ?>
		
		<div class="container-fuild">
			<nav aria-label="breadcrumb">
				<div class="container">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="<?= base_url(); ?>">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">Cancellation Policy</li>
					</ol>
				</div>
			</nav>
		</div> 
		<section class="pro-content login-content">
			<div class="container">
				<div class="row">
					<div class="col-sm-4 mx-auto">
						<center><img src="https://cdn.shopify.com/s/files/1/2337/7003/files/New_Project_12_256x256_crop_center.png?v=1624868361"></center>
						<!--<h1 class="text-center mt-2 pageheading">RETURN AND EXCHANGE POLICY</h1>-->
					</div>  
				</div> 
				<!--<h2 class="text-center pageheading">HOW TO FILE FOR A RETURN OR EXCHANGE?</h2>
				<p class="text-justify">To request for an order cancellation please email us the order # with product name, original proof of purchase receipt and issue at customercare@SlickPattern.pk and our customer care agent will get in contact with you. Alternatively you can call us on +92 316 7776158 from Monday to Saturday between 10:00 am - 6:00 pm (Pakistan Standard Time). Further, to proceed with the case, your purchase should be sent back to us within 14 days of receiving your order.</p>-->
				<?= $list->return_policy ?>
				
				<div class="row">
					<div class="col-sm-6 mx-auto">
						
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<input type="text" class="form-control" placeholder="Order Number">
								</div>
							</div>   
							<div class="col-md-6">
								<div class="form-group">
									<input type="text" class="form-control" placeholder="Email">
								</div>
							</div>   
						</div>	 
						
						<div class="form-group">
							<input type="text" name="product_name" class="form-control" placeholder="Product Name">	 
						</div>
						<div class="form-group">
							<select class="form-control">
								<option value="selected disabled">Request of refund</option>  
							</select> 
						</div>
						<div class="form-group mr-5 ml-5">
							<p class="text-center"><button class="btn btn-secondary btn-block">Send</button></p>	 
						</div>
					</div>  
				</div>
				<br>
				<?= $list->return_policy2;?>
				<!--h2 class="text-center">RETURN PROCEDURE</h2>
				<p class="text-justify">Returns of any order are entertained only if reported within 48 hours of delivery, with original proof of purchase receipt sent to you via email at the time of purchase. To return any item follow below given steps :</p>
				<ul>
					<li>Gather your items & take the picture of those items as proof to share with our customer care team.</li>
					<li>Locate your receipt that is sent to you via email and contains the original order number. Order Confirmations & Receipts are automatically generated by our system and sent out to the email ID provided by the customer once the customer checks out and completes the order purchase process on our website.</li>
					
					<li>Initiate a request for return at SlickPattern’s website by providing your order details that match with your name, email address, and phone number with your reason for return and proof of your claim for return such as pictures, videos, etc.</li>
					
					<li>Customer care team will look into your request, and will contact you if it finds your request genuine and eligible for return.</li>
					<li>Reship it back to us by any courier services if the customer support team agrees with your case.</li>
					<li>After reviewing the nature of the complaint, we may offer you an exchange or store credit of less or equal value with a validity date of the credit.</li>
					<li>In case a return application is approved, it will only be for the price of the article(s), and will not cover the shipping and/or stitching cost.</li>
					<li>In case your claim for return is rejected by customer care, you’ll be notified within 5 business days.</li>
				</ul>
				<br>
				<h2>NOTE:</h2>
				<ul>
				<li>We are only responsible for returns once it reaches our warehouse.</li>	
				<li>Please note returns are catered only if returned products are sent through courier services.</li>	
				<li>All successfully returned items can be exchanged for other merchandise or online store credit. In case of a product being faulty or wrongly delivered, SlickPattern.pk will follow the policy of repair following replacement and finally store credit if the item cannot be repaired or replaced.</li>	
				</ul>
				<p class="text-justify">Timeline for Refund against a returned item : 14 days to 45 days</p>
				<br>
				<h2 class="text-center">EELIGIBILITY CRITERIA FOR A RETURN</h2>
				<ul>
				<li>If your item arrived in defective / damaged or incorrect / incomplete condition, a refund against return will be issued.</li>	
				<li>Incorrect product has been delivered.</li>	
				<li>The product received is incomplete.</li>	
				</ul>
				<br>
				<h2 class="text-center">NON ELIGIBILITY CRITERIA FOR A RETURN</h2>
				<ul>
				<li>Return if the item is "No longer needed" or "Changed my mind" or "no technical reason but just want to cancel the order" or "you do not like the product after opening the package'* any other reasons listed apart from the ones listed in 'Eligibility'.</li>	
				<li>Any *Made to order* or *Customized orders* can not be returned. All 'Made to orders' /Customized orders are shown to the customers before dispatching/shipping out the orders. This is done to ensure that customers get what they ordered. Only after the quality check and approval from the customers, products are shipped to them.</li>	
				<li>Any orders where a customer has been given a special discount as a favor can not be returned.</li>	
				<li>SlickPattern does not cater returns reported after the first 48 hours of delivery.</li>	
				<li>If a product is returned to SlickPattern Warehouse in an inadequate condition or if the product is tempered, damaged or the care instructions have been violated, we reserve the right to send it back to you or refuse to issue the refund.</li>	
				</ul>
				<br>
				<h2 class="text-center">EXCHANGE PROCEDURE</h2>
				<p class="text-justify">At SlickPattern, we are committed to ensuring the highest level of service. Whilst we hope you are delighted with your order, we do not offer any return of exchange under normal conditions. We only offer Conditional Exchange if you face quality issues with the product.</p>
				<p class="text-justify">SlickPattern urges you to file for exchange of product if reported within 48 hours of order confirmation/ delivery. To file an application for exchange kindly follow below given steps :</p>
				<ul>
				<li>Contact our customer care via WhatsApp number, or Email Id provided on the website.</li>	
				<li>Share the link of the outfit that you want to exchange your previous outfit with our customer care team.</li>	
				<li>Confirm your exchange by providing desired size guidelines or customizations.</li>	
				<li>You will receive exchange confirmation within the next 24 to 48 hours.</li>	
				
				</ul>
				<br>
				<h2 class="text-center">EXCHANGE PROCEDURE</h2>
				<p class="text-justify">At SlickPattern, we are committed to ensuring the highest level of service. Whilst we hope you are delighted with your order, we do not offer any return of exchange under normal conditions. We only offer Conditional Exchange if you face quality issues with the product.</p>
				<p class="text-justify">SlickPattern urges you to file for exchange of product if reported within 48 hours of order confirmation/ delivery. To file an application for exchange kindly follow below given steps :</p>
				<ul>
				<li>Contact our customer care via WhatsApp number, or Email Id provided on the website.</li>	
				<li>Share the link of the outfit that you want to exchange your previous outfit with our customer care team.</li>	
				<li>Confirm your exchange by providing desired size guidelines or customizations.</li>	
				<li>You will receive exchange confirmation within the next 24 to 48 hours.</li>	
				
				</ul>
				<br>
				<h2 class="text-center">NON ELIGIBILITY CRITERIA FOR AN EXCHANGE</h2>
				<ul>
				<li>SlickPattern holds the right to not amend/ edit orders after 48 hours of purchase confirmation.</li>	
				<li>Items ordered on sale are not entertained for exchange or return.</li>	
				</ul>
				<h2 class="text-center">PLEASE NOTE</h2>
				<p class="text-justify">SlickPattern will not cater exchange for any product that has been washed, dried, damaged or stained in any way. This includes items that have been dried or damaged in the dryer.</p>
				<p class="text-justify">SlickPattern is not responsible for bleeding, damage of print or fading of colors due to washing and ironing.</p>
				
				
				
				
				
				<h2 class="text-center">FOR ASSISTANCE</h2>
				<div class="text-center">
				<span><a href="tel: 0987654321">CALL : +910987654321</span>	<span class="fa fa-pipe"></span> <span><a href="mailto: slickpattern@gmail.com">EMAIL : slickpattern@gmail.com</span>
				</div-->
				</div>
				</section>
				
				
				
				
				
				
				<?php include('include/footer.php'); ?>
				
				
				
				<?php include('include/jsLinks.php'); ?>
				
				</body>
				</html>																																						