
<!DOCTYPE html>
<html class="no-js" lang="zxx">
	
	<head>
		<meta charset="UTF-8">
		<title>Title</title>
		<meta name="description" content="Description">
		<meta name="keywords" content="Keyword">
		<meta name="author" content="">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<?php include('include/cssLinks.php') ?>
		<style>
			.icon {
			font-size: 2rem;
			}	
			.slide-toggle{
			display:none!important;
			}
			
		</style>
		
	</head>
    
    <body>  
		<!-- Paste this code after body tag -->
		
		
		<!-- //Header Style One -->
		
		<?php include('include/header.php') ?>
		
		<div class="container-fuild">
			<nav aria-label="breadcrumb">
				<div class="container">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="<?= base_url(); ?>"><i class="bi bi-house-door"></i></a></li>
						<li class="breadcrumb-item active" aria-current="page">Termsandconditions</li>
					</ol>
				</div>
			</nav>
		</div> 
		
		
		<section class="pro-content login-content">
			<div class="container"> 
				
				
				<div class="row">
					<div class="col-12 col-sm-12 col-md-12 col-lg-12">
						<div class="card">
							<div class="card-header">
								<h4 class="text-center text-dark" style="font-family: Montserrat-Bold, sans-serif;
								font-weight: normal;">SLICKPATTERN CLUB PROGRAM: TERMS & CONDITIONS</h4>	
							</div>	
							<div class="card-body">
								<div class="clubTnC-main-container">
									<div class="clubTnC-main-wrapper">
										<div class="static_con">
											<div class="head_con">
												<h1>SLICKPATTERN Club Program: Terms &amp; Conditions</h1>
												<div class="sprite_arrow_btm sprite-st_terms">&nbsp;</div>
											</div>
											
											<div class="clubTnC-content">
												<div class="clubTnC_about tncPara">
													<p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p><br>
													<p>Please read the following terms and conditions very carefully as your use of service is subject to your acceptance of and compliance with the following terms and conditions.</p>
												</div>
												
												<div class="clubtnC_block tncPara">
													<div class="clubtnC_heading">1. Definitions</div>
													<ul>
														<li>The domain name and trademark SLICKPATTERN.com is registered in the name of Brainbees Solutions Private Limited (hereinafter referred to as "BSPL"), a company incorporated under the Companies Act, 1956. Digital Age Retail Private Limited, a company incorporated under the Companies Act, 1956 holds a valid license, granted by BSPL, to use and operate the website/Apps (hereinafter referred to as "DARP"). SLICKPATTERN Club Program is a program owned by BSPL which has been licensed for use to DARP on the website/ app and Retail Store/s.  The terms "Us" and "Our" shall mean DARP.</li>
														<li>"SLICKPATTERN Club Program" is a loyalty program to reward and facilitate SLICKPATTERN's loyal users by offering certain privileges/benefits/facilities. </li>
														<li>"SLICKPATTERN Club membership" is a Club membership offered to Users which shall be governed by rules framed hereunder by BSPL for this program which shall be subject to changes from time to time without any prior notification to the SLICKPATTERN User.</li>
														<li>"Platforms" shall mean the domain name www.SLICKPATTERN.com available through www.SLICKPATTERN.com website and mobile application available on android and iOS platform.</li>
														<li>Product" shall mean all Product/s sold on the Platform and Retail Store.</li>
														<li>"Retail Store" shall mean offline SLICKPATTERN retail stores across India. </li>
														<li>"User" or "You" or "Your" shall mean any natural or legal person who at free will has agreed to become a buyer on the platform by providing data while registering on the platform as a registered user and has agreed to enroll for SLICKPATTERN Club membership on successful payment of Membership fees under the terms and conditions contained herein.</li>
													</ul>
												</div>
												
												<div class="clubtnC_block tncPara">
													<div class="clubtnC_heading">2. General Terms</div>
													<ul>
														<li>The terms and conditions stipulated herein shall govern the SLICKPATTERN Club Program and form a binding agreement. If you sign up for the SLICKPATTERN Club membership program either through Website and/or Retail Store, you hereby agree to accept these terms and conditions in their entirety.<br>The terms and conditions mentioned herein has been exclusively formulated for registered users"â„¢ in addition to and shall be read in conjunction to "<a href="https://www.SLICKPATTERN.com/termsofuse" target="_blank">Terms of Use</a>", "<a href="https://www.SLICKPATTERN.com/privacypolicy" target="_blank">Privacy Policy</a>", "<a href="https://www.SLICKPATTERN.com/returnpolicy" target="_blank">Return</a> &amp; <a href="https://www.SLICKPATTERN.com/cancellation-terms" target="_blank">Cancellation Policy</a>" and other applicable legal documents available on the Platform and/or Retail Store which shall continue to be binding on such registered users"â„¢</li>
														<li>DARP may send you email and other communications related to Club and your Club membership. By enrolling into SLICKPATTERN Club membership, it would be deemed that you have given us your consent to contact you through call, SMS or email on the details provided by you for the purpose of availing SLICKPATTERN Club membership.</li>
														<li>You acknowledge and confirm that You are aware of the nature of telecommunications/ internet services and that an email transmission may not be received properly and may be read or be known to any unauthorized persons. You agree to assume and bear all the risks involved in respect of such errors and misunderstanding and DARP shall not be responsible in any manner.</li>
													</ul>
												</div>
												<div class="clubtnC_block tncPara">
													<div class="clubtnC_heading">3. Membership Terms</div>
													<ul>
														<li>You can avail SLICKPATTERN Club membership benefits only by enrolling into a Club membership under SLICKPATTERN Club Program.</li>
														<li>The User can enroll for SLICKPATTERN Club membership through online payment only on Platform and any available payment mode in Retail Stores.</li>
														<li>The duration of the current SLICKPATTERN Club membership plans offered by DARP is for 3 months (90 days), 6 months (180 days) and 12 months (365 days) duration. A User can choose one out of of three plans to join SLICKPATTERN Club membership. DARP may choose to introduce more plans with different tenures in the future or modify the tenures of the current SLICKPATTERN Club membership plans.</li>
														<li>Membership once activated cannot be transferred, canceled, refunded or returned except due to technical reasons, duplicate orders of SLICKPATTERN Club membership are placed. In this case, one membership will be canceled and the user will be refunded the money paid while enrolling for SLICKPATTERN Club membership.</li>
														<li>SLICKPATTERN Club membership is linked to the user"™ SLICKPATTERN account Email id and Mobile number. At any point in time, only one SLICKPATTERN Club membership will be activated per User.</li>
														<li>The User shall have an option to upgrade from 3 months SLICKPATTERN Club membership to 6 months or 12 months SLICKPATTERN Club membership or 6 months SLICKPATTERN memebrship to 12 months SLICKPATTERN Club membership.The upgraded option will not be available immediately, but only after some days from the date of enrolment. A user will be notified through different modes of communication, including but not limited to SMS, Email, Push Notifications, Banners, once the upgrade option is made available.In a lifetime, a User can enroll for any number of SLICKPATTERN Club memberships but the new membership will start only after the expiry of the current membership.</li>
														<li>To avail Club membership benefits, the User needs to login with his/her registered email id/mobile no. on the Platform and share registered mobile no. for identification at the time of purchase at the Retail Stores.</li>
														<li>Club membership cannot be shared or transferred to another User. If a User has shared his/her account details with another User to share the benefits of the Club membership, SLICKPATTERN will not be responsible whatsoever if any benefit under Club membership is being misused/exhausted by such another User.</li>
														<li>The date on which the User has enrolled the Club membership or got the free Club membership from SLICKPATTERN, (subject to clause 4.b) shall be the start date of the membership.</li>
														<li>Club end date would be calculated from the Club start date by adding the membership duration. E.g. For 3 months Club membership user, the membership will end on the last day of the 3rd membership month (90th Day).</li>
														<li>Post the expiry of the current membership, the membership will end, if not renewed.</li>
														<li>In following cases the User shall not be eligible to enroll into SLICKPATTERN Club membership to avail benefits:
															<ul class="subcondition">
																<li>if the User Account has already been marked as a "Fraudulent Account" </li>
															</ul>
															and the User who has already been enrolled into SLICKPATTERN Club membership shall be debarred from availing benefits under the SLICKPATTERN Club membership in case of following events:
															<ul class="subcondition">
																<li>If any fraudulent activity undertaken by the User from his/her Account, such User Account shall be marked as a "Fraudulent Account" </li>
																<li>if Pincode which pertains to delivery address saved/marked by the User on the platform is marked as "Unserviceable" <br>
																DARP shall have discretionary right to modify the existing criteria to categorize a User Account as a Fraudulent Account from time to time to ensure efficient and legitimate usage of the SLICKPATTERN Club membership and the Platform by the genuine User.</li>
															</ul>
														</li>
														<li>The savings shown on the Club Savings Calculator are the basis of the estimated savings on the
														current Club user's data. Actual savings may vary for a user.</li>
													</ul>
												</div>
												<div class="clubtnC_block tncPara">
													<div class="clubtnC_heading">4. Membership Fees</div>
													<ul>
														<li>To check the SLICKPATTERN Club membership fee (hereinafter referred as "Fee") visit the Club landing page to check the available membership options and their corresponding prices . DARP shall at our sole discretion revise the fee charged, and unless specifically stated otherwise, is inclusive of applicable taxes. The Fee once paid by the User at the time of enrollment to SLICKPATTERN Club membership is not-refundable and the SLICKPATTERN Club membership cannot be canceled once the fees is paid.</li>
														<li>Users may get a discount under 3-months or 12-months SLICKPATTERN Club membership, which shall be subject to the criteria formulated by DARP, who shall have discretionary right to modify or nullify the discount rate or modify any other terms and conditions stipulated herein from time to time.</li>
													</ul>
												</div>
												<div class="clubtnC_block tncPara">
													<div class="clubtnC_heading">5. Membership Activation</div>
													<ul>
														<li>Your paid Club membership will be activated only on successful payment for SLICKPATTERN Club membership made through the Platform and/or Retail Stores.</li>
														<li>Your free SLICKPATTERN Club membership shall be subject to the fulfillment of free membership criteria, and shall be activated automatically on the next day of being eligible for free membership criteria at our sole discretion.</li>
													</ul>
												</div>
												<div class="clubtnC_block tncPara">
													<div class="clubtnC_heading">6. Membership Conditions</div>
													<ul>
														<li>DARP reserve the right to terminate, withdraw, suspend, amend, extend or modify SLICKPATTERN Club membership, at our sole discretion without any prior written intimation to the User.</li>
														<li>SLICKPATTERN Club membership or any benefits thereunder are not transferable.</li>
														<li>Club members may not use their membership to purchase Products for the purpose of resale or rental, and the Club services may not be used by any party for commercial purposes.</li>
														<li>DARP may, at our sole discretion, choose to modify the benefits provided under the SLICKPATTERN Club program. Our failure to insist upon or enforce strict compliance with these terms will not constitute a waiver of any of its rights under contract, law or equity.</li>
														<li>Our directors, employees, and agents shall not be liable for any direct, indirect, special, incidental, consequential or punitive damages, or any other damages of any kind, arising out of or related to the SLICKPATTERN Club Program.</li>
													</ul>
												</div>
												<div class="clubtnC_block tncPara">
													<div class="clubtnC_heading">7. Right to Modification of T&amp;C of Membership</div>
													<p>DARP shall at our own discretion change the terms and conditions referred herein, conditions of use, conditions of sale and privacy notice, or any aspect of SLICKPATTERN Club membership, without serving any prior notice to you.</p>
													<p>If any change to these terms is found invalid, void, or for any reason unenforceable under contract, law or equity, that change is severable and does not affect the validity and enforceability of any remaining changes or conditions.</p>
												</div>
												<div class="clubtnC_block tncPara">
													<div class="clubtnC_heading">8. Membership Termination</div>
													<p>DARP may terminate the "Club" membership of a User, at its sole discretion, without serving any prior notice to the User, if the User engages in conduct that violates these terms or any applicable law, or involves fraud or misuse of the Club membership, or is harmful to our interests or any other user on the Platform.</p>
												</div>
												<div class="clubtnC_block tncPara">
													<div class="clubtnC_heading">9. Membership Benefits</div>
													<ul>
														<li>DARP offer a host of benefits to 3 months, 6 months, and 12 months Club users which can be availed either
															on the Platform or at the Retail Stores or on both. DARP reserves the right to modify/remove current benefits
														and to decide on the availability of newly added/modified benefits to the existing Club users, as it seems fit.</li>
														<li>DARP may choose to remove any benefit (from the current list) for the new Users who are buying the
															membership or for the existing Users. For existing Club Users, the benefit may/may not be removed/may be
														modified as per the policy of DARP.</li>
													</ul>
													<p>Details on SLICKPATTERN Club membership benefits are given below:</p>
													<div class="benefits-block">
														<div class="benefits-subheading">(i) Exclusive Discount pricing:</div>
														<ul>
															<li>Club members will be eligible to get an additional discount of up to 5% on the Products, on Products on which the extra Club discount is available as depicted on the Platform and Retail Stores. This additional discount will be available on top of the Product discount provided for non-club users. Products with additional discounts will be shown with two prices- Club &amp; Non-Club on different sections of the Platform and Retail Stores.</li>
															<li>This benefit does not apply to apparel (fashion) products for Retail Stores. For apparel products,
																offering of a discount may be as per the Retail Stores"™discretion.Exclusive discounting price is
																applicable to a User who has enrolled for 3 months, 6 months and 12 months SLICKPATTERN Club
															membership.</li>
														</ul>
														<!-- <a href="https://www.SLICKPATTERN.com/termsofuse#hd3" target="_blank">Read more about SLICKPATTERN's pricing policy</a> -->
													</div>
													<div class="benefits-block xxx">
														<div class="benefits-subheading">(ii) Premium Offers &amp; Deals:</div>
														<p>Premium offers &amp; deals benefits include:</p>
														<ul class="prm">
															<li>Additional coupon discounts: Club users will be eligible to get additional discounts on specific coupons. Additional discounts, if available, will be shown in the coupon terms and conditions.</li>
															<li>Exclusive Club only coupons: DARP will offer few coupons which can be used only by the Club users to get benefits. These coupons will not be available for non-club users to use.</li>
															<li>Additional discount on bank offers: From time to time, DARP brings exciting offers on
																Cards/Wallets/UPI for our users. Club users will get additional benefits on instant
																discount/cashback offers provided by the associated partner. Additional bankdiscount/cashback, if available, will be shown in the offer terms and conditions.Premium
																Offers and Deals are applicable to a User who has enrolled for 3 months, 6 months, and
															12 months SLICKPATTERN Club membership.</li>
														</ul>
														<a href="https://www.SLICKPATTERN.com/termsofuse#hd3" target="_blank">Read more about SLICKPATTERN's coupon policy</a>
													</div>
													<div class="benefits-block">
														<div class="benefits-subheading">(iii) Special Sale Events &amp; Access</div>
														<ul>
															<li>DARP will start sale events a few hours early (for both Platforms and Retail Stores) so that Club members can use the sale offers first. DARP reserves the right to decide events to be launched early. Club users will also get the benefit of dedicated sale events- i.e. Sale events dedicated only for Club users.</li>
															<li>The launch time of early sale events may not be the same and can start at different time/days for Platforms and Retail Stores.</li>
															<li>Platforms and Retail Stores may choose to run dedicated sale events on their own in
																terms of the time of launch, duration of sale events, Product discounts, coupon discounts,
																and Products offered on discounts. These events do not need to be available on both
																businesses. Special Sale Events and access is applicable to a user who has enrolled for
															3 months, 6 months, and 12 month SLICKPATTERN Club membership.</li>
														</ul>
													</div>
													<div class="benefits-block">
														<div class="benefits-subheading">(iv) Discount on Intellikit Subscription</div>
														<ul>
															<li>Club users will get up to an additional 10% discount on Intellikit Subscription bought from the Platform or from Retail Stores.</li>
															<li>This discount is applicable on an Intellikit subscription only and not on Intellikit boxes
																bought separately.Discount on Intellikit Subscription is applicable to a User who has
															enrolled for 3 months, 6 months, and 12 month SLICKPATTERN Club membership.</li>
														</ul>
													</div>
													<div class="benefits-block">
														<div class="benefits-subheading">(v) Club Cash (CC) benefit on products</div>
														<ul>
															<li>As a part of this benefit, 3 months &amp; 6 months Club Users will get Club Cash on products
																as per the Club Cash allocation logic of SLICKPATTERN and 12 months Club Users will get 2 X
																Club Cash, compared to the Club Cash that would have been credited, if they were 3-
															months or 6-monthsclub members.</li>
															<li>This additional Club Cash will be credited to User account post the delivery of the order,
															as per our policy</li>
															<li>Club Cash points earned during Club membership will be available to use post the expiry
																of the membership as well. However, these Club Cash, like all the Club Cash points
															earned on SLICKPATTERN.com, are also subjected to expiry as per our <a href="https://www.SLICKPATTERN.com/termsofuse#hd8" target="_blank">policy</a>.</li>
														</ul>
													</div>
													<div class="benefits-block">
														<div class="benefits-subheading">(vi) Free assembly service</div>
														<ul>
															<li>12 Months Club Users will get Assembly Service free of cost, which is chargeable for
															other types of users.</li>
															<li>Free service will only be available on SLICKPATTERN serviceable pincodes and select Products.
																Users can check the serviceability by entering the pincode on the product details page or
																cart. This benefit is not applicable to 3 months and 6 months SLICKPATTERN Club membership
															Users.</li>
														</ul>
													</div>
													<div class="benefits-block">
														<div class="benefits-subheading">(vii) Shipping Cost benefit</div>
														<strong>For 3 months Club users:</strong>
														<ul>
															<li>A fixed shipping charge of Rs. 50 is applicable on all orders below Rs. 499/-(Rs. 699 for non-club users) (excluding Convenience charges, COD charges, Shipping charges, Taxes, or value reduced after application of coupons or any other offer) at all locations with an additional charge applicable at certain locations.</li>
															<li>For orders equal to or above Rs. 499 (Excluding Convenience charges, COD charges, Shipping charges, Taxes, or value reduced after application of coupons or any other offer) free shipping is available at certain locations only. For other locations, additional shipping charges will be applicable. At these locations, in which additional charges are applicable, the Rs. 50 shipping charges will be added to the shipping charges for all orders below Rs. 499 (with exclusions as above).</li>
															<li>The shipping charge applicable can be checked by entering your pin code details on the cart.</li>
															<li>These shipping charges applicable are not refundable in case of return/cancellation of the product or the order by the user.</li>
															<li>The shipping charges can be modified by DARP at our sole discretion without any prior intimation to the User.</li>
														</ul>
														<strong>For 6 months &amp; 12 months Club Users:</strong>
														<ul>
															<li>For 6 months &amp; 12 months Club Users, the shipping for Products ordered on the
																Platforms is completely free. But the minimum order value to place an order on SLICKPATTERN
															remains the same for both club and non-club users- i.e. Rs. 249</li>
															<li>For 3-months, 6-moths, and 12-months Club Users, the shipping cost benefit is not
																applicable on Convenience and COD charges. These charges will still be applied on
															some orders, as per policy formulated by DARP.</li>
														</ul>
														<!-- <a href="https://www.SLICKPATTERN.com/shippingpolicy" target="_blank">Read more about SLICKPATTERN's shipping policy</a> -->
													</div>
													<div class="benefits-block">
														<div class="benefits-subheading">(viii) Free SLICKPATTERN Playbees App Subscription</div>
														<ul>
															<li>Club Users will get a free subscription of the SLICKPATTERN Playbees edutainment app's 'Basic'
															plan for the Club membership duration.</li>
															<li>The start date and the end date of the Playbees app subscription would be the same as
															the Club membership dates.</li>
															<li>If the Club User already has paid subscription fee of the Playbees app, the free
																subscription would start only after the expiry of term of the currently paid subscription
															period.</li>
															<li>Irrespective of the edutainment app subscription start date, the subscription will expire
															after the Club membership ends.</li>
														</ul>
													</div>
													<div class="benefits-block">
														<div class="benefits-subheading">(ix) Exclusive store coupons</div>
														<ul>
															<li>SLICKPATTERN users can avail the Store coupons benefit till the Club membership expiry.</li>
															<li>Coupons will be shared with Users via SMS on their registered mobile number post its
															activation.</li>
															<li>The first coupon worth Rs. 100 will be activated and sent to the Users within a few hours
															of enrollment into the Club membership.</li>
															<li>The next/subsequent coupon will have an additional Rs. 100 discount.</li>
															<li>The next/subsequent coupon will unlock/generate only after the use of the previous
															coupon.</li>
															<li>The next/subsequent coupon unlock/generation doesn’t mean the coupon is available for
																immediate use. The store coupon will be active/available only within the validity tenure
																shared with users via SMS. The SMS would contain the validity tenure details. SLICKPATTERN
															users can also refer to the Club dashboard for active coupon details.</li>
															<li>Each coupon validity will be of 30 days only, if the current coupon is not used within the shared validity tenure, the current coupon validity will get extended for the next 30 days and the last coupon will get lapsed. The coupon validity extension details will be shared with users via SMS. For example, if a 3-month club user uses his 1st coupon in the last month of his/her club membership, the user won't get the 2nd &amp; 3rd store coupon since the user missed the 2-validity cycle. The coupon lapsing cycle will continue whenever the current coupon is not used within the validity tenure/time.</li>
															<li>SLICKPATTERN users can use only one coupon per month.</li>
															<li>3-months, 6-months, and 12-Months Club users will get up to 3, 6 and 12 coupons
															respectively subjected to the monthly usage condition mentioned above.</li>
															<li>The coupons are only applicable on Babyhug and Cutewalk clothes and shoes.</li>
															<li>Store coupons can be used at Retail Stores only and cannot be used on online platform</li>
															<li>When a user successfully refers a new user, he/she will receive a 1-month extension to his/her membership and an additional store coupon worth Rs.100. However, the validity of any existing store coupons will not be extended and will expire post its validity tenure.</li>
														</ul>
													</div>
													<div class="benefits-block">
														<div class="benefits-subheading">(X) Brand Benefit/Premium Subscription (3 rd Party Offer or
														"Reward/Benefit")</div>
														<ul>
															<li>Brand Benefit &amp; Premium Subscription benefit plan is a type of exclusive 3 rd party
																reward for Club users in which the Club Users will receive certain rewards/ benefits in an
																ongoing Club membership period. Brand Benefit &amp; Premium Subscription benefit plan
															shall be activated at the time of activation of Club membership.</li>
															<li>Reward/Benefit can be redeemed on the exclusive and relevant 3 rd party merchant's app
																or website as per the given T&amp;C provided by the merchant. Club User may find the terms
																and conditions for a reward/benefit on the Club Dashboard page by selecting the relevant
																reward/ benefit. Reward/Benefits are valid subject to availability of products/services with
															third party merchant.</li>
															<li>The Club User shall ensure their complete discretion for availing benefits from
															rewards/offers provided by third party merchants.</li>
															<li>Reward/Benefits shall not be settled with cash in lieu by DARP or the Partner(s), and are
															not transferable.</li>    
															<li>DARP is not endorsing the third-party merchants or the reward/ benefits offered by the
															third-party merchants</li>
															<li>Any and all the benefits offered by the third-party merchants are subject to the third- party
															merchant's terms and conditions.</li>
															<li>DARP reserves the right to modify or terminate Brand Benefits/Premium Subscription
																Benefits at any time without any prior notice to the Club User and without any liability or
															obligation in this regard.</li>
															<li>In case of fraudulent use of third-party merchant's offers by the Club User, DARP
																reserves the right to withdraw the third-party merchant's offers/benefits earned by the
															Club user.</li>
															<li>Benefits are for Club users only and are non-transferable and must be used in a lawful
																manner. For such activities, DARP reserves the right to withdraw the third party
															offers/benefits earned by the Club user.</li>
															<li>Club Users are not bound in any way to participate in this third-party merchant's offer. Any
															participation is voluntary and the benefits are being provided purely on a best effort basis.</li>    
															<li>Any dispute or queries related to a third-party Benefits shall be addressed by the third-
																party merchant of which the Club User had desired to avail benefit from. In the event of
																failure of Club User to avail any benefit from Rewards/Offers of third-party merchant,
																DARP shall not be responsible in any manner whatsoever to the Club User as the User
																understands that rewards/offers and their applicable terms and conditions are formulated
																by the third-party merchants. Further, DARP disclaims all liabilities, responsibilities,
																representations and warranties of any kind, whether express or implied, including, but not
																limited to, the warranties of any materials or content, quality, merchantability, suitability,
																missed services, features related to third party rewards/offers offered by third party
																merchants and their products/services and DARP shall not be responsible for any direct,
																indirect, incidental damages caused due to use of reward/offers towards
															products/services offered and usage of products/services offered by third-party merchant.</li>
															<li>All statutory taxes (direct or indirect, including local levies, TDS, registration fees,
																Insurance) on the Brand Benefit &amp; Premium Subscription Benefits, wherever applicable,
															shall be payable by the Club User. DARP will not be responsible / liable for the same.</li>
															<li>The third-party rewards/offers are valid during the term of SLICKPATTERN Club. membership
																plans enrolled by the Club User i.e., for 3 months (90 days) and 12 months (365 days)
															duration.</li>       
															<li>Club User hereby agree to indemnify and keep DARP harmless against all damages,
																liabilities, costs, expenses, claims, suits and proceedings (including reasonable attorney's
																fee) that may be suffered by DARP as a consequence of (i) violation of terms of this T&amp;C
																by Club User; (ii) violation of applicable laws; (iii) any action or inaction resulting in willful
															misconduct or negligence on Club User's part.</li>         
															<li>The savings shown on the Club Savings Calculator are the basis of the estimated savings
																on the current Club user's data and do not reflect accurate value of savings of the Club
															User. Actual savings may vary for a Club user.</li>    
														</ul>
													</div>
												</div>
												<div class="clubtnC_block tncPara">
													<div class="clubtnC_heading">10. Refer &amp; Earn - Club Program</div>
													<p>Please read these Terms and Conditions carefully before participating in the Refer &amp; Earn - Club
														Program ("the Program") provided by SLICKPATTERN. By participating in the Program, you agree to be
													bound by these Terms and Conditions.</p>
													<div class="benefits-block refer_earn_block">
														<div class="benefits-subheading">(i) Eligibility:</div>
														<ul>
															<li>The Program is available only to Club Users ("Referrers") who have subscribed to 3, 6, and12 month plans.</li>
															<li>Non-Club members ("Referees") are eligible to use referral codes to avail a discount on their next Club membership purchase.</li>
														</ul>
														<div class="benefits-subheading">(ii) Referral Process:</div>
														<ul>
															<li>Referrers will have a unique referral code that they can share with Referees.</li>
															<li>A successful referral is counted when a non-Club member uses the unique referral code to purchase a Club membership.</li>
															<li>Referrers will receive a 1-month extension on their current Club membership tenure and an additional store coupon worth Rs. 100 per successful referral.</li>
															<li>Referees will receive an additional discount on their Club membership purchase by using the referral code provided by the Referrers.</li>
															<li>The referral code will be valid until the ongoing Club membership of the Referrer expires.</li>
															<li>The referral reward will be credited to the referrer's account within 24 hours of the referee successfully joining the club program.</li>
														</ul>
														<div class="benefits-subheading">(iii) Additional Store Coupons:</div>
														<ul>
															<li>Each additional store coupon earned through successful referrals will have its own validity period.</li>
															<li>Only one additional store coupon can be used in a month.</li>
															<li>If multiple coupons are earned, they must be used within their respective validity periods; otherwise, the coupons will lapse.</li>
															<li>1 additional coupon will be provided to user per referral and will be valid for only 30 days and the validity period will be shared to users via SMS.</li>
															<li>When a user successfully refers a new user, he/she will receive a 1-month extension to his/her membership and an additional store coupon worth Rs.100. However, the validity of any existing store coupons will not be extended and will expire post its validity tenure.</li>
														</ul>
														<div class="benefits-subheading">(iv) Referral Log:</div>
														<ul>
															<li>Referrers can check the log of their referred friends by following these steps:
																<ul class="refrl_block">
																	<li>Redirect to the Club Dashboard Page.</li>
																	<li>Click on the Invite button in the Refer &amp; Earn section visible.</li>
																	<li>You will be redirected to the Refer &amp; Earn - Club page.</li>
																	<li>Click on the Referrals sub-section to view the log of referred friends who
																	have successfully joined the Club.</li>
																</ul>
															</li>
															<li>The log will include information about the friends referred, their successful Club membership purchases, and the respective dates and times of joining Club.</li>
														</ul>
														<div class="benefits-subheading">(v) Referral Code Usage:</div>
														<ul>
															<li>Referrers can invite as many friends as they want, as long as the friends are not existing Club members.</li>
															<li>Referral codes can be used only by non-Club members to avail discounts on their next Club membership purchase.</li>
														</ul>
														<div class="benefits-subheading">(vi) General Terms:</div>
														<ul>
															<li>The Company reserves the right to modify or terminate the Program at any time without prior notice.</li>
															<li>The Company reserves the right to disqualify participants who violate these Terms and Conditions or engage in fraudulent or unethical behavior.</li>
															<li>The Company's decisions regarding the Program, including the eligibility of referrals and the issuance of rewards, are final and binding.</li>
															<li>Participation in the Program is voluntary, and participants acknowledge that they do not have any claim against the Company for any loss or damage arising from their participation.</li>
														</ul>
														<p>By participating in the Program, you acknowledge that you have read, understood, and agreed to these Terms and Conditions</p>
													</div>
												</div>
											</div>
										</div></div>
								</div>
							</div>
						</div>
						<!--h1 class="pageheading">Term & Condition for slickpattern</h1>
							
							<p class="text-justify">At slickpattern, accessible from http://slickpattern.digitalcoders.in/, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by slickpattern and how we use it.</p>
							
							<p class="text-justify">If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>
							
							<p class="text-justify">This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in slickpattern. This policy is not applicable to any information collected offline or via channels other than this website. Our Privacy Policy was created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/">Free Privacy Policy Generator</a>.</p>
							
							<h2>Consent</h2>
							
							<p class="text-justify">By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>
							
							<h2>Information we collect</h2>
							
							<p class="text-justify">The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information.</p>
							<p class="text-justify">If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide.</p>
							<p class="text-justify">When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number.</p>
							
							<h2>How we use your information</h2>
							
							<p class="text-justify">We use the information we collect in various ways, including to:</p>
							
							<ul>
							<li>Provide, operate, and maintain our website</li>
							<li>Improve, personalize, and expand our website</li>
							<li>Understand and analyze how you use our website</li>
							<li>Develop new products, services, features, and functionality</li>
							<li>Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes</li>
							<li>Send you emails</li>
							<li>Find and prevent fraud</li>
							</ul>
							
							<h2>Log Files</h2>
							
							<p class="text-justify">slickpattern follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.</p>
							
							<h2>Cookies and Web Beacons</h2>
							
							<p class="text-justify">Like any other website, slickpattern uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.</p>
							
							<p class="text-justify">For more general information on cookies, please read <a href="https://www.termsfeed.com/blog/sample-cookies-policy-template/#What_Are_Cookies">the Cookies article on TermsFeed website</a>.</p>
							
							
							
							<h2>Advertising Partners Privacy Policies</h2>
							
							<p class="text-justify">You may consult this list to find the Privacy Policy for each of the advertising partners of slickpattern.</p>
							
							<p class="text-justify">Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on slickpattern, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>
							
							<p class="text-justify">Note that slickpattern has no access to or control over these cookies that are used by third-party advertisers.</p>
							
							<h2>Third Party Privacy Policies</h2>
							
							<p class="text-justify">slickpattern's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. </p>
							
							<p class="text-justify">You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.</p>
							
							<h2>CCPA Privacy Rights (Do Not Sell My Personal Information)</h2>
							
							<p class="text-justify">Under the CCPA, among other rights, California consumers have the right to:</p>
							<p class="text-justify">Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</p>
							<p class="text-justify">Request that a business delete any personal data about the consumer that a business has collected.</p>
							<p class="text-justify">Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</p>
							<p class="text-justify">If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>
							
							<h2>GDPR Data Protection Rights</h2>
							
							<p class="text-justify">We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:</p>
							<p class="text-justify">The right to access – You have the right to request copies of your personal data. We may charge you a small fee for this service.</p>
							<p class="text-justify">The right to rectification – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete.</p>
							<p class="text-justify">The right to erasure – You have the right to request that we erase your personal data, under certain conditions.</p>
							<p class="text-justify">The right to restrict processing – You have the right to request that we restrict the processing of your personal data, under certain conditions.</p>
							<p class="text-justify">The right to object to processing – You have the right to object to our processing of your personal data, under certain conditions.</p>
							<p class="text-justify">The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</p>
							<p class="text-justify">If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>
							
							<h2>Children's Information</h2>
							
							<p class="text-justify">Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>
							
						<p class="text-justify">slickpattern does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p-->
						
					</div>
				</div>
				
			</div>
		</section>
		
		
		
		
		
		
		<?php include('include/footer.php'); ?>
		
		
		
		<?php include('include/jsLinks.php'); ?>
		
	</body>
</html>																						